### ISSUE TITLE
Breaks page -- var() does not work inside calc() [FireFox 67]

### ISSUE THREAD

**Issue by brandonkal** [lusakasa/saka-key#261]
When Saka is enabled, CSS variables do not work inside of calc() in Firefox. The issue appears that the injected element with these styles
```css
  div#saka-gui-root {
  position: absolute;
  left: 0px;
  top: 0px;
  width: 100%;
  height: 100%;
  z-index: 2147483647;
  opacity: 1;
}
```

is causing the entire page to render as the body color at the top when the html height is smaller than the viewport.

This appears related to https://github.com/lusakasa/saka-key/issues/256 as that page is only accessible if the window is made to be extremely short (i.e.) 200px, and scrolling past the white element.
